# Generated by Django 2.2.7 on 2019-11-29 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Education',
            new_name='Educations',
        ),
    ]
