# Generated by Django 2.2.7 on 2019-11-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_auto_20191129_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Education_name', models.CharField(max_length=245)),
                ('Education_university', models.CharField(max_length=245)),
                ('Education_year', models.CharField(max_length=245)),
                ('Education_obtainedmarks', models.CharField(max_length=4)),
                ('Education_maxmarks', models.CharField(max_length=4)),
                ('Education_per', models.CharField(max_length=4)),
                ('Education_remarks', models.CharField(max_length=245)),
                ('Education_user_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Educations',
        ),
    ]
